/**
 * Curated clichés — phrases so worn that they no longer make a reader see
 * anything. Organised by family so additions land somewhere sensible.
 *
 * Rules for inclusion:
 *   - Multi-word. Single tired words belong in weakWords.ts.
 *   - Lowercase, letters/apostrophes/hyphens only; matching is token-based
 *     and ignores punctuation between words.
 *   - Dead enough that flagging it in *fiction* is almost never wrong.
 *     Phrases that are fine in dialogue but tired in narration are still
 *     included: the writer decides, the plugin only points.
 */
export const CLICHES: readonly string[] = [
  // --- time and inevitability ---
  "at the end of the day", "in the nick of time", "only time will tell", "time will tell",
  "time heals all wounds", "time stood still", "in this day and age", "as old as time",
  "since the dawn of time", "the sands of time", "at this moment in time", "when all is said and done",
  "at the eleventh hour", "better late than never", "in the blink of an eye",
  "before you know it", "a race against time", "the calm before the storm", "from time immemorial",
  "last but not least", "the moment of truth", "the end of an era",
  "in the heat of the moment", "in the fullness of time", "all in good time",

  // --- fate, luck, struggle ---
  "against all odds", "the odds were stacked against", "beat the odds", "a stroke of luck",
  "the luck of the draw", "a blessing in disguise", "every cloud has a silver lining", "a silver lining",
  "the light at the end of the tunnel", "light at the end of the tunnel", "a glimmer of hope",
  "a ray of hope", "hope against hope", "the writing on the wall", "the writing was on the wall",
  "a sign of the times", "what goes around comes around", "it is what it is",
  "the straw that broke the camel's back", "the last straw", "the final straw", "a bitter pill to swallow",
  "a tough pill to swallow", "the bitter end", "to the bitter end",
  "it's not rocket science", "it's not brain surgery", "the tip of the iceberg", "like the plague", "avoid like the plague", "just the tip of the iceberg",
  "a perfect storm", "the perfect storm", "a double-edged sword", "a slippery slope", "a vicious circle",
  "a vicious cycle", "a catch-twenty-two", "a necessary evil", "the lesser of two evils", "a fate worse than death",
  "a matter of life and death", "only a matter of time", "a ticking time bomb",
  "playing with fire", "a recipe for disaster", "an accident waiting to happen", "a disaster waiting to happen",
  "a leap of faith", "a shot in the dark", "a needle in a haystack", "the elephant in the room",
  "a can of worms", "opened a can of worms", "between a rock and a hard place", "caught between a rock and a hard place",
  "out of the frying pan and into the fire", "out of the frying pan", "the best of both worlds", "the worst of both worlds",
  "a win-win situation", "a lose-lose situation", "a no-brainer", "the name of the game",

  // --- people and character ---
  "a diamond in the rough", "a heart of gold", "a heart of stone", "a tower of strength", "a pillar of the community",
  "a force to be reckoned with", "a force of nature", "larger than life", "a man of few words", "a woman of few words",
  "the salt of the earth", "the strong silent type", "a shoulder to cry on", "a wolf in sheep's clothing",
  "a sheep in wolf's clothing", "a fish out of water", "a big fish in a small pond", "a small fish in a big pond",
  "the black sheep of the family", "the black sheep", "a chip off the old block", "a bundle of nerves",
  "a bundle of joy", "a ball of energy", "a breath of fresh air", "a sight for sore eyes", "a pain in the neck",
  "a thorn in my side", "a thorn in his side", "a thorn in her side", "a thorn in their side", "a loose cannon",
  "a dark horse", "a lone wolf", "a free spirit", "an old soul", "a people person", "a go-getter",
  "a mover and shaker", "movers and shakers", "the life of the party", "the life and soul of the party",
  "a jack of all trades", "armed to the teeth", "dressed to kill", "dressed to the nines", "fit as a fiddle",
  "right as rain", "sharp as a tack", "dumb as a post", "mad as a hatter", "stubborn as a mule",
  "strong as an ox", "quiet as a mouse", "sly as a fox", "blind as a bat", "busy as a bee", "cool as a cucumber",
  "happy as a clam", "free as a bird", "snug as a bug", "light as a feather", "white as a sheet",
  "white as snow", "pale as a ghost", "red as a beet", "black as night", "black as coal", "black as pitch",
  "cold as ice", "hard as nails", "hard as a rock", "tough as nails", "old as the hills", "dead as a doornail",
  "dead as a dodo", "flat as a pancake", "thin as a rail", "thick as thieves", "pretty as a picture",
  "clear as crystal", "clear as day", "clear as mud", "plain as day", "good as gold", "good as new",
  "solid as a rock", "steady as a rock", "clean as a whistle", "slow as molasses", "quick as a flash",
  "quick as lightning", "fast as lightning", "like a bat out of hell", "like a deer in the headlights",
  "like a deer caught in the headlights", "like a kid in a candy store", "like a fish out of water",
  "like a bull in a china shop", "like a moth to a flame", "like a hot knife through butter",
  "like a ton of bricks", "like a house on fire", "like a chicken with its head cut off", "like there's no tomorrow",
  "like there was no tomorrow", "like clockwork", "like a dream", "like a charm", "like water off a duck's back",
  "like two peas in a pod", "like taking candy from a baby", "like a broken record", "like night and day",
  "like a glove", "fit like a glove", "like the back of my hand", "like the back of his hand",
  "like the back of her hand", "like a sore thumb", "stuck out like a sore thumb", "stick out like a sore thumb",

  // --- body and emotion (the fiction specials) ---
  "a chill ran down my spine", "a chill ran down his spine", "a chill ran down her spine", "a chill ran down their spine",
  "a shiver ran down my spine", "a shiver ran down his spine", "a shiver ran down her spine", "sent shivers down my spine",
  "sent shivers down his spine", "sent shivers down her spine", "sent a chill down", "sent a shiver down",
  "my heart skipped a beat", "his heart skipped a beat", "her heart skipped a beat", "heart skipped a beat",
  "my heart was in my throat", "his heart was in his throat", "her heart was in her throat", "heart in my throat",
  "heart in his throat", "heart in her throat", "my heart pounded in my chest", "his heart pounded in his chest",
  "her heart pounded in her chest", "heart pounding in my chest", "heart pounding in his chest", "heart pounding in her chest",
  "my heart sank", "his heart sank", "her heart sank", "my blood ran cold", "his blood ran cold", "her blood ran cold",
  "blood ran cold", "my blood boiled", "his blood boiled", "her blood boiled", "made my blood boil", "made his blood boil",
  "made her blood boil", "a lump in my throat", "a lump in his throat", "a lump in her throat", "butterflies in my stomach",
  "butterflies in his stomach", "butterflies in her stomach", "my stomach dropped", "his stomach dropped", "her stomach dropped",
  "the pit of my stomach", "the pit of his stomach", "the pit of her stomach", "a knot in my stomach", "a knot in his stomach",
  "a knot in her stomach", "a sinking feeling", "a wave of relief", "a wave of nausea", "a wave of panic", "a flood of relief",
  "a flood of emotion", "a flood of memories", "a surge of adrenaline", "a rush of adrenaline", "a pang of guilt",
  "a pang of jealousy", "a twinge of guilt", "a twinge of regret", "let out a breath i didn't know i was holding",
  "let out a breath he didn't know he was holding", "let out a breath she didn't know she was holding",
  "a breath i didn't know i was holding", "a breath he didn't know he was holding", "a breath she didn't know she was holding",
  "released a breath", "let out a sigh of relief", "breathed a sigh of relief", "time seemed to stand still", "the world stood still", "the world fell away",
  "everything went black", "the room began to spin", "the room started to spin", "the world came crashing down",
  "my world came crashing down", "his world came crashing down", "her world came crashing down", "fell to pieces",
  "fell apart at the seams", "coming apart at the seams", "tears streamed down my face", "tears streamed down his face",
  "tears streamed down her face", "tears welled up", "tears welled in", "a single tear", "a single tear rolled",
  "a single tear slid", "cried my eyes out", "cried his eyes out", "cried her eyes out", "cried like a baby",
  "eyes like saucers", "eyes wide as saucers", "eyes as big as saucers", "a deer in the headlights",
  "a twinkle in his eye", "a twinkle in her eye", "a sparkle in his eye", "a sparkle in her eye", "eyes lit up",
  "his eyes lit up", "her eyes lit up", "a gleam in his eye", "a gleam in her eye", "piercing blue eyes",
  "orbs of", "emerald orbs", "sapphire orbs", "chocolate orbs", "a smile played on his lips", "a smile played on her lips",
  "a smile tugged at his lips", "a smile tugged at her lips", "a smile tugged at the corner", "the corners of his mouth",
  "the corners of her mouth", "a grin spread across his face", "a grin spread across her face", "grinned from ear to ear",
  "a smile from ear to ear", "smiled from ear to ear", "a ghost of a smile", "a smirk played",
  "bit my lip", "bit his lip", "bit her lip", "bit my tongue", "bit his tongue", "bit her tongue", "ran a hand through his hair",
  "ran a hand through her hair", "ran his fingers through his hair", "ran her fingers through her hair",
  "raked a hand through his hair", "raked a hand through her hair", "shook his head in disbelief", "shook her head in disbelief", "shook my head in disbelief",
  "rolled my eyes", "rolled his eyes", "rolled her eyes", "crossed my arms", "crossed his arms", "crossed her arms",
  "clenched my fists", "clenched his fists", "clenched her fists", "clenched his jaw", "clenched her jaw",
  "gritted my teeth", "gritted his teeth", "gritted her teeth", "through gritted teeth", "through clenched teeth",
  "a deafening silence", "deafening silence", "the silence was deafening", "an awkward silence", "an uncomfortable silence",
  "a pregnant pause", "you could cut the tension with a knife", "cut the tension with a knife", "thick with tension",
  "tension so thick", "the air was thick with", "the air was electric", "electricity in the air", "sparks flew",
  "sparks flying", "the chemistry between", "a magnetic pull", "drawn to him like", "drawn to her like",
  "fell head over heels", "head over heels", "love at first sight", "swept off my feet", "swept off his feet",
  "swept off her feet", "swept her off her feet", "swept him off his feet", "weak in the knees", "went weak at the knees",
  "stole my breath", "stole his breath", "stole her breath", "took my breath away", "took his breath away",
  "took her breath away", "breathtakingly beautiful", "drop-dead gorgeous", "a vision in", "the girl next door",
  "the boy next door", "tall dark and handsome", "a knight in shining armour", "a knight in shining armor",
  "a damsel in distress", "happily ever after", "the one that got away", "a match made in heaven", "it was meant to be", "written in the stars", "the love of my life", "the love of his life",
  "the love of her life", "my better half", "his better half", "her better half", "the apple of my eye",
  "the apple of his eye", "the apple of her eye", "head over heels in love", "madly in love",

  // --- violence, fear, action ---
  "fight or flight", "a fight to the death", "a knock-down drag-out", "all hell broke loose", "hell broke loose",
  "armed and dangerous", "a sitting duck", "sitting ducks", "a bloodbath", "a hail of bullets", "in the line of fire",
  "in the crosshairs", "dodged a bullet", "bit the bullet", "went down swinging", "down for the count",
  "a cat and mouse game", "a game of cat and mouse", "cat and mouse", "on the edge of my seat", "on the edge of his seat",
  "on the edge of her seat", "on the edge of their seats", "on pins and needles", "on tenterhooks", "a nail-biter",
  "nail-biting", "the hairs on the back of my neck", "the hairs on the back of his neck", "the hairs on the back of her neck",
  "the hair on the back of my neck stood up", "hair stood on end", "scared out of my wits", "scared out of his wits",
  "scared out of her wits", "scared stiff", "scared to death", "frightened to death", "frozen with fear",
  "frozen in fear", "paralysed with fear", "paralyzed with fear", "rooted to the spot", "jumped out of my skin",
  "jumped out of his skin", "jumped out of her skin", "my skin crawled", "his skin crawled", "her skin crawled",
  "made my skin crawl", "made his skin crawl", "made her skin crawl", "a cold sweat", "broke out in a cold sweat",
  "shaking like a leaf", "trembling like a leaf", "shook like a leaf", "it was a dark and stormy night",
  "a dark and stormy night", "dark and stormy", "the dead of night", "in the dead of night", "the witching hour",
  "bump in the night", "things that go bump in the night", "eerily quiet", "an eerie silence",
  "bone-chilling", "chilled to the bone", "spine-chilling", "spine-tingling", "blood-curdling", "a blood-curdling scream",
  "hair-raising", "every fibre of my being", "every fiber of my being", "every fibre of his being", "every fiber of his being",
  "every fibre of her being", "every fiber of her being", "with every fibre", "with every fiber", "with every ounce of",
  "every ounce of strength", "with all my might", "with all his might", "with all her might", "fought tooth and nail",
  "tooth and nail", "no holds barred", "took no prisoners", "take no prisoners", "a fighting chance", "come hell or high water",
  "hell or high water", "over my dead body", "a bolt from the blue", "out of the blue", "like a bolt from the blue",
  "a lightning bolt", "from out of nowhere", "in the thick of it", "in the thick of things",
  "the eye of the storm", "weathered the storm", "weather the storm", "any port in a storm", "a storm was brewing",
  "a storm is brewing", "the gathering storm", "the heavens opened", "rain came down in sheets", "cats and dogs",
  "raining cats and dogs", "a wall of water", "a sea of faces", "a sea of people", "a sea of red", "a sea of green",

  // --- narration crutches ---
  "little did i know", "little did he know", "little did she know", "little did they know", "needless to say",
  "it goes without saying", "suffice it to say", "suffice to say", "to make a long story short", "long story short",
  "to cut a long story short", "the rest is history", "and the rest is history", "as luck would have it",
  "as fate would have it", "lo and behold", "much to my surprise", "much to his surprise", "much to her surprise",
  "much to my dismay", "much to his dismay", "much to her dismay", "to my horror", "to his horror", "to her horror",
  "for all intents and purposes", "for all intensive purposes", "in a manner of speaking", "so to speak",
  "for what it's worth", "for what it is worth", "all things considered", "in the grand scheme of things",
  "the grand scheme of things", "in the scheme of things", "the big picture", "the whole nine yards", "the whole shebang",
  "the whole enchilada", "the whole kit and caboodle", "lock stock and barrel", "each and every", "first and foremost",
  "few and far between", "by leaps and bounds", "in leaps and bounds", "part and parcel", "tried and true",
  "tried and tested", "safe and sound", "alive and well", "alive and kicking", "sick and tired", "short and sweet",
  "nice and easy", "slowly but surely", "quietly but firmly", "gently but firmly", "wined and dined",
  "ranted and raved", "kicking and screaming", "hemmed and hawed", "tossed and turned", "hustle and bustle",
  "the hustle and bustle", "bright-eyed and bushy-tailed", "signed sealed and delivered", "cut and dried", "cut and dry",
  "hit the ground running", "hit the nail on the head", "hit rock bottom", "hit the sack", "hit the hay", "hit the road",
  "hit the books", "hit the jackpot", "hit it off", "hit home", "the truth hit me", "the truth hit him", "the truth hit her",
  "it hit me like", "it hit him like", "it hit her like", "dawned on me", "dawned on him", "dawned on her", "it dawned on",
  "the realisation hit", "the realization hit", "the realisation dawned", "the realization dawned", "the penny dropped",
  "a light bulb went off", "a lightbulb went off", "a light bulb moment", "food for thought", "a train of thought",
  "lost my train of thought", "lost his train of thought", "lost her train of thought", "thoughts raced", "my mind raced",
  "his mind raced", "her mind raced", "mind racing", "a million thoughts", "a thousand thoughts", "a million miles an hour",
  "a million miles away", "a thousand miles away", "lost in thought", "deep in thought", "snapped out of it",
  "snapped back to reality", "back to reality", "jolted back", "came crashing back", "reality set in", "reality sank in", "it finally sank in", "the gravity of the situation", "the weight of the world", "the weight of the world on",
  "carried the weight of the world", "a weight lifted", "a weight off my shoulders", "a weight off his shoulders",
  "a weight off her shoulders", "a burden lifted",
  "crossed that bridge", "cross that bridge when", "burn that bridge", "burned his bridges", "burned her bridges",
  "water under the bridge", "no stone unturned", "leave no stone unturned", "left no stone unturned", "a stone's throw",
  "a stone's throw away", "a hop skip and a jump", "in the same boat", "rocked the boat",
  "rock the boat", "missed the boat", "jumped ship", "abandon ship", "all hands on deck", "a sinking ship",
  "rats leaving a sinking ship", "smooth sailing", "plain sailing", "uncharted waters", "uncharted territory",
  "troubled waters", "test the waters", "tested the waters", "muddy the waters", "in deep water", "in hot water",
  "dead in the water", "blood in the water", "go with the flow", "went with the flow", "against the current",
  "swimming against the tide", "turn the tide", "turned the tide", "the tide turned", "the tide had turned",
  "a sea change", "ebb and flow", "the ebb and flow", "a drop in the ocean", "a drop in the bucket", "the floodgates opened",
  "opened the floodgates", "a watershed moment", "a pivotal moment", "a defining moment", "at a crossroads", "a fork in the road", "the road less travelled", "the road less traveled",
  "the road not taken", "a bump in the road", "the end of the road", "the end of the line", "a dead end",
  "hit a dead end", "a roadblock", "hit a wall", "hit a brick wall", "back to square one", "back to the drawing board", "in the driver's seat", "in the driving seat", "asleep at the wheel", "a wake-up call",
  "a rude awakening", "a reality check", "a wake up call", "a slap in the face", "a kick in the teeth", "a punch in the gut",
  "a gut punch", "like a punch to the gut", "a kick in the stomach", "a stab in the back", "stabbed in the back",
  "twist the knife", "twisted the knife", "salt in the wound", "rubbed salt in the wound", "add insult to injury",
  "added insult to injury", "to add insult to injury", "kicked when he was down", "kicked when she was down",

  // --- stock description ---
  "a picture-perfect", "picture perfect", "a picturesque", "nestled in", "nestled among", "nestled between",
  "a sprawling", "sun-drenched", "sun-kissed", "moonlit night", "a blanket of snow", "a blanket of fog",
  "a carpet of", "a sea of stars", "a canopy of stars", "a million stars", "twinkling stars",
  "the stars twinkled", "a crescent moon", "a full moon hung", "the moon hung", "the sun beat down",
  "the sun beat down mercilessly",
  "the sun dipped below the horizon", "dipped below the horizon", "the golden hour", "bathed in golden light", "bathed in moonlight", "bathed in sunlight", "dappled sunlight", "dappled light", "shafts of light",
  "shafts of sunlight", "a shaft of light", "a beam of light", "the crack of dawn", "at the crack of dawn", "the first light of dawn", "the break of dawn", "the wee hours", "the wee small hours",
  "the still of the night", "a lone figure", "a solitary figure", "a shadowy figure", "a figure emerged", "emerged from the shadows",
  "lurking in the shadows", "lurked in the shadows", "cloaked in darkness", "shrouded in darkness", "shrouded in mystery",
  "cloaked in mystery", "veiled in mystery", "an air of mystery", "exuded an air of", "a riot of colour", "a riot of color",
  "an explosion of colour", "an explosion of color", "a kaleidoscope of", "a tapestry of", "a rich tapestry",
  "a patchwork of", "a symphony of", "a cacophony of", "a chorus of", "a whirlwind of", "a whirlwind romance",
  "a flurry of activity", "a hive of activity", "a beehive of activity", "a melting pot", "the crown jewel",
  "a hidden gem", "a well-kept secret", "a best-kept secret", "off the beaten path", "off the beaten track",
  "a stone's throw from", "a home away from home", "a labour of love", "a labor of love", "a labyrinth of",
  "a maze of", "a warren of", "rolling hills", "the rolling hills", "a sleepy village",
  "a sleepy town", "a quaint little", "a cozy little", "a cosy little", "a bustling city", "the bustling city",
  "the concrete jungle", "the urban jungle", "the city that never sleeps", "the big apple", "the windy city",
  "in the middle of nowhere", "the middle of nowhere", "off the grid", "the back of beyond", "the ends of the earth",
  "the four corners of the earth", "the four corners of the globe", "every corner of the globe", "far and wide",
  "near and far", "high and low", "searched high and low",
];
