/**
 * Figures so conventional they no longer produce an image. Matched as
 * phrases; the concreteness rule handles the novel-but-maybe-tired cases.
 */
export const DEAD_METAPHORS: readonly string[] = [
  "a flood of", "a wave of", "a sea of", "a mountain of", "a river of", "an ocean of", "a torrent of", "a storm of",
  "a blanket of", "a curtain of", "a wall of", "a web of", "a tangle of", "a cloud of", "a shadow of", "a spark of",
  "a flame of", "a fire of", "a glimmer of", "a flicker of", "a flash of", "a ray of", "a beam of", "a shaft of",
  "an iron grip", "an iron will", "an iron fist", "a heart of gold", "a heart of stone", "a heavy heart",
  "a broken heart", "a warm welcome", "a cold shoulder", "a cold reception", "a bitter taste", "a sweet victory",
  "a burning desire", "a burning question", "a crushing blow", "a crushing defeat", "a shattered dream",
  "shattered dreams", "a sinking feeling", "a rising tide", "the tide of", "the winds of change", "the sands of",
  "the fabric of", "the seeds of", "the roots of", "the fruits of", "the heart of the matter", "the bones of",
  "the skeleton of", "the backbone of", "the lifeblood of", "the cornerstone of", "the bedrock of", "the foundation of",
  "the pillar of", "the anchor of", "the engine of", "the machinery of", "the wheels of", "the gears of",
  "the architecture of", "the landscape of", "the terrain of", "the map of", "the road to", "the path to",
  "the journey of", "the door to", "the gateway to", "the key to", "the window into", "the mirror of",
  "the lens of", "the spectrum of", "the shadow of", "the light of", "the dawn of", "the twilight of",
  "the birth of", "the death of", "the grave of", "the ghost of", "the spirit of", "the soul of", "the face of",
  "the voice of", "the hand of", "the arm of", "the eye of", "the mouth of", "the teeth of", "the jaws of",
  "the grip of", "the clutches of", "the weight of", "the burden of", "the chains of", "the shackles of",
  "the prison of", "the cage of", "the trap of", "the web of", "the net of", "the maze of", "the labyrinth of",
  "the fog of", "the mist of", "the haze of", "the veil of", "the mask of", "the cloak of", "the armour of",
  "the armor of", "the shield of", "the sword of", "the blade of", "the knife of", "the wound of", "the scar of",
  "the poison of", "the cancer of", "the disease of", "the plague of", "the virus of", "the cure for",
  "the medicine of", "the balm of", "the salve of", "the food of", "the hunger for", "the thirst for",
  "the appetite for", "a taste of", "a taste for", "the flavour of", "the flavor of", "the scent of", "the smell of",
  "the music of", "the song of", "the dance of", "the rhythm of", "the melody of", "the harmony of", "the silence of",
  "the echo of", "the whisper of", "the roar of", "the thunder of", "the storm of", "the calm of", "the stillness of",
  "time flies", "time marches on", "time is money", "time ran out", "running out of time", "money talks",
  "the clock is ticking", "love is blind", "love is a battlefield", "life is a journey", "life is a highway",
  "life is a rollercoaster", "a rollercoaster of", "an emotional rollercoaster", "drowning in", "buried under",
  "swimming in", "bathed in", "wrapped in", "cloaked in", "shrouded in", "steeped in", "soaked in", "dripping with",
  "oozing with", "bursting with", "brimming with", "overflowing with", "bubbling with", "boiling with", "seething with",
  "simmering with", "crackling with", "humming with", "buzzing with", "alive with", "thick with", "heavy with",
  "laden with", "pregnant with", "ripe with", "rich with", "riddled with", "plagued by", "haunted by", "consumed by",
  "devoured by", "eaten up by", "torn apart by", "ripped apart by", "crushed by", "broken by", "shattered by",
  "blinded by", "deafened by", "paralysed by", "paralyzed by", "frozen by", "gripped by", "seized by", "struck by",
  "hit by", "washed over", "swept over", "came over", "crept over", "crept in", "crept up", "sank in", "set in",
  "took hold", "took root", "took flight", "took shape", "took form", "came to light", "came to life", "came alive",
  "opened up", "shut down", "closed off", "walled off", "melted away", "faded away", "drained away", "ebbed away",
  "slipped away", "washed away", "swept away", "carried away", "blown away", "bowled over", "knocked out",
  "knocked down", "cut down", "cut off", "cut through", "cut deep", "ran deep", "ran cold", "ran hot", "ran dry",
  "ran wild", "ran free", "ran high", "burned bright", "burned out", "burned up", "burned through", "lit up",
  "light up", "lit a fire", "fanned the flames", "added fuel to the fire", "fuel to the fire", "playing with fire",
  "sea of faces", "a mountain to climb", "an uphill battle", "an uphill struggle", "a long road", "a rocky road",
  "a bumpy road", "a dead end", "a fork in the road", "a crossroads", "a turning point", "a stepping stone",
  "a springboard", "a launchpad", "a gateway", "a doorway", "a window of opportunity", "a golden opportunity",
  "a silver bullet", "a magic bullet", "a double-edged sword", "a two-edged sword", "a slippery slope",
  "a house of cards", "a ticking bomb", "a time bomb", "a powder keg", "a minefield", "a battlefield", "a war zone",
  "a jungle", "a zoo", "a circus", "a madhouse", "a nightmare", "a dream come true", "a living hell", "hell on earth",
  "heaven on earth", "a slice of heaven", "a breath of fresh air", "a ray of sunshine", "a shot in the arm",
  "a kick in the teeth", "a slap in the face", "a punch in the gut", "a stab in the back", "a thorn in the side",
  "a pain in the neck", "a weight off", "a load off", "a chip on", "a monkey on", "an albatross around",
  "a millstone around", "an anchor around", "a cloud over", "a shadow over", "a question mark over", "a cloud hanging",
];
